= gun_cookies_list(3)

== Name

gun_cookies_list - Cookie store backend: in-memory, per connection

== Description

The `gun_cookies_list` module implements a cookie store
backend that keeps all the cookie data in-memory and tied
to a specific connection.

It is possible to implement a custom backend on top of
`gun_cookies_list` in order to add persistence or sharing
properties. Note that it is the responsibility of the
custom backend to provide cookies that conform to RFC6265
if they come from external sources (e.g. files), especially
for the `name`, `value`, `domain` and `path` fields.

== Exports

This module implements the callbacks defined in
link:man:gun_cookies(3)[gun_cookies(3)].

== Types

=== opts()

[source,erlang]
----
opts() :: #{
    max_cookies => non_neg_integer() | infinity
}
----

Cookie store backend options.

The default value is given next to the option name:

max_cookies (50)::

Maximum number of cookies kept in the store. When
the limit is reached, expired cookies are dropped
first, then cookies with the earliest last-access-time.
The value `infinity` disables the limit.

== Changelog

* *2.6*: The `max_cookies` option was added.
* *2.0*: Module introduced.

== Examples

.Open a connection with a cookie store configured
[source,erlang]
----
{ok, ConnPid} = gun:open(Host, Port, #{
    cookie_store => gun_cookies_list:init(#{})
})
----

== See also

link:man:gun(7)[gun(7)],
link:man:gun_cookies(3)[gun_cookies(3)]
